name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependency
      run: sudo apt update && sudo apt install libudev-dev
    - name: Build
      run: cargo build --release --verbose
